# File Path: .github/workflows/ccpp_win.yml

name: C/C++ Nightly Windows x64

on:
  push:
    branches:
      - nightly
      - nightly_dev
      - nightly_master
      - debug_win
      - rcx
      - master
      - main
      - add-velocity-extrusion

jobs:
  build_dep:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v4
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Create build directory
        run: mkdir deps/build
      - name: Build dependencies
        working-directory: ./deps/build
        run: |
          cmake .. -G "Visual Studio 16 2019" -A x64
          msbuild /m ALL_BUILD.vcxproj
      - name: Upload dependency artifacts
        uses: actions/upload-artifact@v4.0.0
        with:
          name: deps_win
          path: ./deps/build/destdir/

  build:
    runs-on: windows-2019
    needs: build_dep

    steps:
      - uses: actions/checkout@v4
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Update submodules
        working-directory: ./resources/profiles
        run: git submodule update --init
      - name: Update version date
        shell: powershell
        run: (Get-Content version.inc) | ForEach-Object {$_ -replace "\+UNKNOWN", ("_" + [datetime]::Today.ToString("yyyy-MM-dd"))} | Set-Content version.inc
      - name: Create directory for dependencies
        run: mkdir deps/destdir
      - name: Download dependencies
        uses: actions/download-artifact@v4
        with:
          name: deps_win
          path: deps/destdir
      - name: Prepare build directory
        run: mkdir build
      - name: Configure project
        working-directory: ./build
        run: cmake .. -G "Visual Studio 16 2019" -A x64 -DCMAKE_PREFIX_PATH="d:\a\${{ github.event.repository.name }}\${{ github.event.repository.name }}\deps\destdir\usr\local"
      - name: Build project
        working-directory: ./build
        run: msbuild /m /P:Configuration=RelWithDebInfo INSTALL.vcxproj
      - name: Build .mo files
        working-directory: ./build
        run: msbuild /m /P:Configuration=RelWithDebInfo gettext_po_to_mo.vcxproj
      - name: Build .pot files
        working-directory: ./build
        run: msbuild /m /P:Configuration=RelWithDebInfo gettext_make_pot.vcxproj
      - name: Create package directory
        working-directory: ./build
        shell: powershell
        run: mkdir package
      - name: Download prebuilt resources
        working-directory: ./build
        shell: powershell
        run: '(New-Object System.Net.WebClient).DownloadFile("https://github.com/supermerill/SuperSlicer_deps/releases/download/1.75/Slic3r_win_build.zip", "Slic3r_win_build.zip")'
      - name: Extract prebuilt resources
        working-directory: ./build
        shell: cmd
        run: '"C:/Program Files/7-Zip/7z.exe" x Slic3r_win_build.zip'
      - name: Copy missing DLLs
        working-directory: ./build
        shell: cmd
        run: |
          xcopy /RCYIE Slic3r_win_build\*.dll package\
          xcopy /RCYIE Slic3r_win_build\local-settings.bat package\${{ github.event.repository.name }}_local-settings.bat
          xcopy /RCYIE Slic3r_win_build\mesa package\
      - name: Copy resources
        working-directory: ./build
        shell: cmd
        run: xcopy /RCYIE ..\resources package\resources
      - name: Copy executables and DLLs
        working-directory: ./build
        shell: cmd
        run: |
          xcopy /RCYIE src\RelWithDebInfo\*.dll package\
          xcopy /RCYIE src\RelWithDebInfo\*.exe package\
          xcopy /RCYIE c:\windows\system32\VCRUNTIME140* package\
          del package\opengl32.dll
      - name: Upload packaged artifact
        uses: actions/upload-artifact@v4.0.0
        with:
          name: nightly_win64
          path: build/package/
